import { Recipe } from './types';

// Base de recettes placeholder — à valider par diététicienne avant mise en prod
// Format conforme au schéma Supabase (CLAUDE.md §9)

export const RECIPES_PLACEHOLDER: Recipe[] = [
  {
    id: 'r001',
    name_fr: 'Omelette blanche au fromage blanc',
    prep_time_min: 8,
    portions: 1,
    macros_per_portion: { kcal: 320, protein_g: 38, carbs_g: 6, fat_g: 16 },
    ingredients: [
      { name: 'Blancs d\'œuf', quantity_g: 200 },
      { name: 'Fromage blanc 0%', quantity_g: 100 },
      { name: 'Sel, poivre', quantity_g: 2 },
    ],
    steps: [
      'Battre les blancs d\'œuf avec sel et poivre.',
      'Cuire dans une poêle antiadhésive 3 min.',
      'Ajouter le fromage blanc au centre, plier et servir.',
    ],
    tags: ['breakfast'],
    validated_by_dietitian: false,
  },
  {
    id: 'r002',
    name_fr: 'Flocons d\'avoine protéinés',
    prep_time_min: 5,
    portions: 1,
    macros_per_portion: { kcal: 380, protein_g: 28, carbs_g: 52, fat_g: 6 },
    ingredients: [
      { name: 'Flocons d\'avoine', quantity_g: 80 },
      { name: 'Lait demi-écrémé', quantity_g: 200, unit: 'ml' },
      { name: 'Whey protéine vanille', quantity_g: 30 },
      { name: 'Banane', quantity_g: 60 },
    ],
    steps: [
      'Verser les flocons et le lait dans un bol.',
      'Micro-ondes 2 min, mélanger.',
      'Incorporer la whey et garnir de banane.',
    ],
    tags: ['breakfast'],
    validated_by_dietitian: false,
  },
  {
    id: 'r003',
    name_fr: 'Poulet grillé riz basmati brocolis',
    prep_time_min: 15,
    portions: 1,
    macros_per_portion: { kcal: 520, protein_g: 48, carbs_g: 58, fat_g: 8 },
    ingredients: [
      { name: 'Blanc de poulet', quantity_g: 200 },
      { name: 'Riz basmati cru', quantity_g: 100 },
      { name: 'Brocolis', quantity_g: 150 },
      { name: 'Huile d\'olive', quantity_g: 8 },
      { name: 'Épices au choix', quantity_g: 3 },
    ],
    steps: [
      'Cuire le riz basmati à l\'eau 12 min.',
      'Poêler le poulet 6 min de chaque côté avec épices.',
      'Faire revenir les brocolis 4 min.',
      'Assembler dans un bol.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r004',
    name_fr: 'Saumon riz patate douce',
    prep_time_min: 15,
    portions: 1,
    macros_per_portion: { kcal: 560, protein_g: 42, carbs_g: 54, fat_g: 18 },
    ingredients: [
      { name: 'Pavé de saumon', quantity_g: 180 },
      { name: 'Riz complet cru', quantity_g: 80 },
      { name: 'Patate douce', quantity_g: 120 },
      { name: 'Citron', quantity_g: 20 },
    ],
    steps: [
      'Cuire le riz 12 min à l\'eau.',
      'Enfourner la patate douce 10 min au micro-ondes.',
      'Poêler le saumon 4 min par face avec le citron.',
      'Dresser dans une assiette.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r005',
    name_fr: 'Bowl thon avocat quinoa',
    prep_time_min: 10,
    portions: 1,
    macros_per_portion: { kcal: 490, protein_g: 38, carbs_g: 40, fat_g: 18 },
    ingredients: [
      { name: 'Thon en boîte au naturel', quantity_g: 150 },
      { name: 'Quinoa cuit', quantity_g: 120 },
      { name: 'Avocat', quantity_g: 80 },
      { name: 'Tomates cerises', quantity_g: 80 },
      { name: 'Citron, sel', quantity_g: 10 },
    ],
    steps: [
      'Réchauffer le quinoa 1 min.',
      'Trancher l\'avocat, couper les tomates.',
      'Égoutter le thon.',
      'Assembler le bowl, assaisonner au citron.',
    ],
    tags: ['lunch'],
    validated_by_dietitian: false,
  },
  {
    id: 'r006',
    name_fr: 'Steak haché patate douce salade',
    prep_time_min: 12,
    portions: 1,
    macros_per_portion: { kcal: 510, protein_g: 44, carbs_g: 38, fat_g: 20 },
    ingredients: [
      { name: 'Steak haché 5% MG', quantity_g: 200 },
      { name: 'Patate douce', quantity_g: 150 },
      { name: 'Salade verte', quantity_g: 50 },
      { name: 'Moutarde', quantity_g: 10 },
    ],
    steps: [
      'Cuire la patate douce au micro-ondes 8 min.',
      'Poêler le steak 3 min par face.',
      'Dresser avec la salade et la moutarde.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r007',
    name_fr: 'Fromage blanc protéines amandes',
    prep_time_min: 3,
    portions: 1,
    macros_per_portion: { kcal: 250, protein_g: 22, carbs_g: 14, fat_g: 10 },
    ingredients: [
      { name: 'Fromage blanc 0%', quantity_g: 200 },
      { name: 'Amandes effilées', quantity_g: 20 },
      { name: 'Miel', quantity_g: 10 },
    ],
    steps: [
      'Verser le fromage blanc dans un bol.',
      'Ajouter les amandes et le miel.',
    ],
    tags: ['snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r008',
    name_fr: 'Shake whey banane',
    prep_time_min: 2,
    portions: 1,
    macros_per_portion: { kcal: 290, protein_g: 30, carbs_g: 34, fat_g: 3 },
    ingredients: [
      { name: 'Whey protéine', quantity_g: 30 },
      { name: 'Banane', quantity_g: 100 },
      { name: 'Lait demi-écrémé', quantity_g: 200, unit: 'ml' },
    ],
    steps: [
      'Mixer tous les ingrédients 30 secondes.',
      'Servir immédiatement.',
    ],
    tags: ['snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r009',
    name_fr: 'Pâtes complètes sauce bolognaise maison',
    prep_time_min: 15,
    portions: 1,
    macros_per_portion: { kcal: 590, protein_g: 46, carbs_g: 68, fat_g: 12 },
    ingredients: [
      { name: 'Pâtes complètes crues', quantity_g: 120 },
      { name: 'Bœuf haché 5% MG', quantity_g: 150 },
      { name: 'Sauce tomate', quantity_g: 100 },
      { name: 'Oignon', quantity_g: 50 },
      { name: 'Huile d\'olive', quantity_g: 5 },
    ],
    steps: [
      'Faire revenir l\'oignon dans l\'huile 2 min.',
      'Ajouter le bœuf, cuire 5 min.',
      'Incorporer la sauce tomate, mijoter 5 min.',
      'Cuire les pâtes al dente 8 min, égoutter, mélanger.',
    ],
    tags: ['dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r010',
    name_fr: 'Oeufs brouillés épinards',
    prep_time_min: 8,
    portions: 1,
    macros_per_portion: { kcal: 340, protein_g: 28, carbs_g: 6, fat_g: 22 },
    ingredients: [
      { name: 'Œufs entiers', quantity_g: 180 },
      { name: 'Épinards frais', quantity_g: 80 },
      { name: 'Huile d\'olive', quantity_g: 8 },
      { name: 'Sel, poivre', quantity_g: 2 },
    ],
    steps: [
      'Battre les œufs avec sel et poivre.',
      'Faire revenir les épinards 2 min.',
      'Ajouter les œufs, remuer à feu doux jusqu\'à prise.',
    ],
    tags: ['breakfast', 'dinner'],
    validated_by_dietitian: false,
  },
  // ── Recettes denses en énergie, plus pauvres en protéines ───────────────────
  // (~0.03–0.06 g protéine/kcal) : indispensables pour atteindre la cible
  // protéines des objectifs à faible densité (maintien, prise de masse), où le
  // reste du pool, riche en protéines, ferait déborder les protéines. Plus de
  // glucides/lipides relativement aux protéines (pâtes, riz, oléagineux, fruits).
  {
    id: 'r011',
    name_fr: 'Porridge beurre de cacahuète & banane',
    prep_time_min: 7,
    portions: 1,
    macros_per_portion: { kcal: 660, protein_g: 24, carbs_g: 88, fat_g: 24 },
    ingredients: [
      { name: 'Flocons d\'avoine', quantity_g: 80 },
      { name: 'Beurre de cacahuète', quantity_g: 30 },
      { name: 'Banane', quantity_g: 100 },
      { name: 'Lait demi-écrémé', quantity_g: 200, unit: 'ml' },
    ],
    steps: [
      'Verser les flocons et le lait dans une casserole.',
      'Cuire à feu doux 4 min en remuant jusqu\'à épaississement.',
      'Hors du feu, incorporer le beurre de cacahuète.',
      'Garnir de rondelles de banane et servir.',
    ],
    tags: ['breakfast'],
    validated_by_dietitian: false,
  },
  {
    id: 'r012',
    name_fr: 'Tartine avocat & œuf poché',
    prep_time_min: 10,
    portions: 1,
    macros_per_portion: { kcal: 450, protein_g: 17, carbs_g: 50, fat_g: 20 },
    ingredients: [
      { name: 'Pain complet', quantity_g: 100 },
      { name: 'Avocat', quantity_g: 80 },
      { name: 'Œuf', quantity_g: 50 },
      { name: 'Huile d\'olive', quantity_g: 5 },
      { name: 'Citron, sel, poivre', quantity_g: 5 },
    ],
    steps: [
      'Toaster les tranches de pain complet.',
      'Écraser l\'avocat avec le citron, sel et poivre, étaler sur le pain.',
      'Pocher l\'œuf 3 min dans l\'eau frémissante.',
      'Déposer l\'œuf sur la tartine, filet d\'huile d\'olive.',
    ],
    tags: ['breakfast'],
    validated_by_dietitian: false,
  },
  {
    id: 'r013',
    name_fr: 'Pâtes pesto & parmesan',
    prep_time_min: 12,
    portions: 1,
    macros_per_portion: { kcal: 660, protein_g: 21, carbs_g: 75, fat_g: 31 },
    ingredients: [
      { name: 'Pâtes crues', quantity_g: 100 },
      { name: 'Pesto', quantity_g: 40 },
      { name: 'Parmesan', quantity_g: 15 },
      { name: 'Pignons de pin', quantity_g: 10 },
    ],
    steps: [
      'Cuire les pâtes al dente 9 min, réserver un peu d\'eau de cuisson.',
      'Égoutter et mélanger au pesto, détendre avec l\'eau de cuisson.',
      'Parsemer de parmesan râpé et de pignons torréfiés.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r014',
    name_fr: 'Risotto aux champignons',
    prep_time_min: 20,
    portions: 1,
    macros_per_portion: { kcal: 540, protein_g: 16, carbs_g: 78, fat_g: 18 },
    ingredients: [
      { name: 'Riz arborio cru', quantity_g: 90 },
      { name: 'Champignons de Paris', quantity_g: 150 },
      { name: 'Oignon', quantity_g: 40 },
      { name: 'Parmesan', quantity_g: 20 },
      { name: 'Beurre', quantity_g: 15 },
      { name: 'Bouillon de légumes', quantity_g: 300, unit: 'ml' },
    ],
    steps: [
      'Faire revenir l\'oignon et les champignons.',
      'Ajouter le riz, nacrer 1 min.',
      'Mouiller au bouillon louche par louche en remuant 16 min.',
      'Hors du feu, incorporer beurre et parmesan, servir crémeux.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r015',
    name_fr: 'Curry de pois chiches & riz basmati',
    prep_time_min: 18,
    portions: 1,
    macros_per_portion: { kcal: 630, protein_g: 19, carbs_g: 95, fat_g: 19 },
    ingredients: [
      { name: 'Pois chiches cuits', quantity_g: 150 },
      { name: 'Riz basmati cru', quantity_g: 70 },
      { name: 'Lait de coco', quantity_g: 80, unit: 'ml' },
      { name: 'Épinards frais', quantity_g: 50 },
      { name: 'Pâte de curry & épices', quantity_g: 25 },
    ],
    steps: [
      'Cuire le riz basmati 11 min à l\'eau.',
      'Faire revenir la pâte de curry, ajouter pois chiches et lait de coco.',
      'Mijoter 8 min, incorporer les épinards en fin de cuisson.',
      'Servir le curry sur le riz.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r016',
    name_fr: 'Smoothie avoine, fruits rouges & beurre d\'amande',
    prep_time_min: 3,
    portions: 1,
    macros_per_portion: { kcal: 520, protein_g: 19, carbs_g: 72, fat_g: 17 },
    ingredients: [
      { name: 'Flocons d\'avoine', quantity_g: 40 },
      { name: 'Beurre d\'amande', quantity_g: 20 },
      { name: 'Banane', quantity_g: 100 },
      { name: 'Fruits rouges', quantity_g: 80 },
      { name: 'Lait demi-écrémé', quantity_g: 200, unit: 'ml' },
    ],
    steps: [
      'Verser tous les ingrédients dans un blender.',
      'Mixer 45 secondes jusqu\'à obtenir une texture lisse.',
      'Servir bien frais.',
    ],
    tags: ['breakfast', 'snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r017',
    name_fr: 'Tartine beurre de cacahuète & banane',
    prep_time_min: 4,
    portions: 1,
    macros_per_portion: { kcal: 375, protein_g: 12, carbs_g: 50, fat_g: 14 },
    ingredients: [
      { name: 'Pain complet', quantity_g: 60 },
      { name: 'Beurre de cacahuète', quantity_g: 25 },
      { name: 'Banane', quantity_g: 80 },
    ],
    steps: [
      'Toaster le pain complet.',
      'Étaler le beurre de cacahuète.',
      'Disposer les rondelles de banane par-dessus.',
    ],
    tags: ['snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r018',
    name_fr: 'Riz au lait vanille',
    prep_time_min: 25,
    portions: 1,
    macros_per_portion: { kcal: 395, protein_g: 11, carbs_g: 67, fat_g: 9 },
    ingredients: [
      { name: 'Riz rond', quantity_g: 50 },
      { name: 'Lait entier', quantity_g: 250, unit: 'ml' },
      { name: 'Sucre', quantity_g: 15 },
      { name: 'Vanille', quantity_g: 2 },
    ],
    steps: [
      'Porter le lait et la vanille à frémissement.',
      'Ajouter le riz, cuire à feu doux 20 min en remuant.',
      'Incorporer le sucre, laisser tiédir et servir.',
    ],
    tags: ['snack'],
    validated_by_dietitian: false,
  },
  // ── Recettes à densité protéique intermédiaire (~0.05 g/kcal) ───────────────
  // Comblent l'écart entre le pool riche en protéines (≥0.075) et les recettes
  // pauvres ci-dessus (~0.03). Indispensables pour atteindre PRÉCISÉMENT la
  // cible des objectifs intermédiaires (recomp ~0.067, maintien ~0.052) sans
  // que le choix « variété » n'oscille entre une recette trop/pas assez riche.
  {
    id: 'r019',
    name_fr: 'Chili con carne haricots rouges & riz',
    prep_time_min: 20,
    portions: 1,
    macros_per_portion: { kcal: 560, protein_g: 30, carbs_g: 86, fat_g: 11 },
    ingredients: [
      { name: 'Bœuf haché 5% MG', quantity_g: 70 },
      { name: 'Haricots rouges cuits', quantity_g: 150 },
      { name: 'Riz basmati cru', quantity_g: 60 },
      { name: 'Sauce tomate', quantity_g: 80 },
      { name: 'Oignon', quantity_g: 40 },
      { name: 'Épices chili', quantity_g: 4 },
    ],
    steps: [
      'Cuire le riz basmati 11 min à l\'eau.',
      'Faire revenir l\'oignon, ajouter le bœuf et les épices, cuire 5 min.',
      'Incorporer haricots rouges et sauce tomate, mijoter 8 min.',
      'Servir le chili sur le riz.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r020',
    name_fr: 'Gratin de pâtes au jambon',
    prep_time_min: 22,
    portions: 1,
    macros_per_portion: { kcal: 550, protein_g: 28, carbs_g: 68, fat_g: 18 },
    ingredients: [
      { name: 'Pâtes crues', quantity_g: 90 },
      { name: 'Jambon', quantity_g: 50 },
      { name: 'Lait demi-écrémé', quantity_g: 150, unit: 'ml' },
      { name: 'Emmental râpé', quantity_g: 30 },
      { name: 'Farine', quantity_g: 10 },
      { name: 'Beurre', quantity_g: 10 },
    ],
    steps: [
      'Cuire les pâtes al dente 9 min, égoutter.',
      'Préparer une béchamel avec beurre, farine et lait.',
      'Mélanger pâtes, dés de jambon et béchamel dans un plat.',
      'Couvrir d\'emmental, gratiner 10 min au four.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  // ── Phase 1 : élargissement à 30 recettes ───────────────────────────────────
  // Ajout d'options végétariennes riches en protéines + poisson (pescétarien)
  // pour que les filtres de régime produisent des plans variés, et plus de
  // choix petit-déj / collation. Densités protéiques variées (équilibre du pool).
  {
    id: 'r021',
    name_fr: 'Dahl de lentilles corail',
    prep_time_min: 15,
    portions: 1,
    macros_per_portion: { kcal: 540, protein_g: 24, carbs_g: 82, fat_g: 12 },
    ingredients: [
      { name: 'Lentilles corail crues', quantity_g: 90 },
      { name: 'Riz basmati cru', quantity_g: 50 },
      { name: 'Lait de coco', quantity_g: 60, unit: 'ml' },
      { name: 'Oignon', quantity_g: 40 },
      { name: 'Épices curry', quantity_g: 4 },
    ],
    steps: [
      'Faire revenir l\'oignon avec les épices 2 min.',
      'Ajouter les lentilles, le lait de coco et 200 ml d\'eau, mijoter 12 min.',
      'Cuire le riz à l\'eau 10 min en parallèle.',
      'Servir le dahl sur le riz.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r022',
    name_fr: 'Tofu sauté légumes & nouilles',
    prep_time_min: 12,
    portions: 1,
    macros_per_portion: { kcal: 520, protein_g: 26, carbs_g: 58, fat_g: 18 },
    ingredients: [
      { name: 'Tofu ferme', quantity_g: 150 },
      { name: 'Nouilles', quantity_g: 70 },
      { name: 'Poivrons', quantity_g: 80 },
      { name: 'Sauce soja', quantity_g: 15 },
      { name: 'Huile de sésame', quantity_g: 8 },
    ],
    steps: [
      'Cuire les nouilles selon le paquet.',
      'Saisir le tofu en dés dans l\'huile 4 min.',
      'Ajouter les poivrons, sauter 3 min, verser la sauce soja.',
      'Incorporer les nouilles, mélanger.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r023',
    name_fr: 'Cabillaud, pommes de terre & haricots verts',
    prep_time_min: 15,
    portions: 1,
    macros_per_portion: { kcal: 470, protein_g: 40, carbs_g: 48, fat_g: 10 },
    ingredients: [
      { name: 'Filet de cabillaud', quantity_g: 180 },
      { name: 'Pommes de terre', quantity_g: 200 },
      { name: 'Haricots verts', quantity_g: 120 },
      { name: 'Huile d\'olive', quantity_g: 8 },
      { name: 'Citron', quantity_g: 15 },
    ],
    steps: [
      'Cuire les pommes de terre et haricots verts à la vapeur 12 min.',
      'Poêler le cabillaud 3 min par face avec le citron.',
      'Assaisonner d\'huile d\'olive et servir.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r024',
    name_fr: 'Crevettes ail & riz',
    prep_time_min: 12,
    portions: 1,
    macros_per_portion: { kcal: 460, protein_g: 34, carbs_g: 62, fat_g: 7 },
    ingredients: [
      { name: 'Crevettes décortiquées', quantity_g: 150 },
      { name: 'Riz basmati cru', quantity_g: 80 },
      { name: 'Ail', quantity_g: 6 },
      { name: 'Persil', quantity_g: 5 },
      { name: 'Huile d\'olive', quantity_g: 6 },
    ],
    steps: [
      'Cuire le riz à l\'eau 10 min.',
      'Saisir les crevettes avec l\'ail 4 min.',
      'Parsemer de persil, servir avec le riz.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r025',
    name_fr: 'Œufs cocotte épinards & feta',
    prep_time_min: 12,
    portions: 1,
    macros_per_portion: { kcal: 380, protein_g: 26, carbs_g: 8, fat_g: 27 },
    ingredients: [
      { name: 'Œufs entiers', quantity_g: 150 },
      { name: 'Épinards frais', quantity_g: 100 },
      { name: 'Feta', quantity_g: 40 },
      { name: 'Crème légère', quantity_g: 30 },
    ],
    steps: [
      'Faire tomber les épinards à la poêle 2 min.',
      'Répartir dans un ramequin avec la crème et la feta.',
      'Casser les œufs dessus, enfourner 8 min à 180°C.',
    ],
    tags: ['breakfast', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r026',
    name_fr: 'Salade lentilles, feta & tomates',
    prep_time_min: 8,
    portions: 1,
    macros_per_portion: { kcal: 430, protein_g: 22, carbs_g: 46, fat_g: 16 },
    ingredients: [
      { name: 'Lentilles cuites', quantity_g: 200 },
      { name: 'Feta', quantity_g: 40 },
      { name: 'Tomates', quantity_g: 100 },
      { name: 'Oignon rouge', quantity_g: 30 },
      { name: 'Huile d\'olive', quantity_g: 10 },
    ],
    steps: [
      'Égoutter les lentilles, couper tomates et oignon.',
      'Mélanger avec la feta émiettée.',
      'Assaisonner d\'huile d\'olive.',
    ],
    tags: ['lunch'],
    validated_by_dietitian: false,
  },
  {
    id: 'r027',
    name_fr: 'Skyr, granola & myrtilles',
    prep_time_min: 3,
    portions: 1,
    macros_per_portion: { kcal: 330, protein_g: 24, carbs_g: 45, fat_g: 6 },
    ingredients: [
      { name: 'Skyr', quantity_g: 200 },
      { name: 'Granola', quantity_g: 40 },
      { name: 'Myrtilles', quantity_g: 60 },
      { name: 'Miel', quantity_g: 8 },
    ],
    steps: [
      'Verser le skyr dans un bol.',
      'Ajouter granola, myrtilles et un filet de miel.',
    ],
    tags: ['breakfast', 'snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r028',
    name_fr: 'Wrap poulet & crudités',
    prep_time_min: 10,
    portions: 1,
    macros_per_portion: { kcal: 480, protein_g: 38, carbs_g: 46, fat_g: 14 },
    ingredients: [
      { name: 'Tortilla de blé', quantity_g: 60 },
      { name: 'Blanc de poulet', quantity_g: 130 },
      { name: 'Salade verte', quantity_g: 30 },
      { name: 'Tomate', quantity_g: 50 },
      { name: 'Yaourt nature', quantity_g: 30 },
    ],
    steps: [
      'Poêler le poulet émincé 6 min.',
      'Garnir la tortilla de salade, tomate, poulet et yaourt.',
      'Rouler et servir.',
    ],
    tags: ['lunch'],
    validated_by_dietitian: false,
  },
  {
    id: 'r029',
    name_fr: 'Pancakes flocons & banane',
    prep_time_min: 12,
    portions: 1,
    macros_per_portion: { kcal: 360, protein_g: 15, carbs_g: 56, fat_g: 8 },
    ingredients: [
      { name: 'Flocons d\'avoine', quantity_g: 60 },
      { name: 'Banane', quantity_g: 100 },
      { name: 'Œuf', quantity_g: 50 },
      { name: 'Lait demi-écrémé', quantity_g: 60, unit: 'ml' },
    ],
    steps: [
      'Mixer tous les ingrédients en pâte.',
      'Cuire de petites galettes 2 min par face.',
    ],
    tags: ['breakfast', 'snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r030',
    name_fr: 'Cottage cheese, concombre & pain complet',
    prep_time_min: 5,
    portions: 1,
    macros_per_portion: { kcal: 280, protein_g: 26, carbs_g: 30, fat_g: 6 },
    ingredients: [
      { name: 'Cottage cheese', quantity_g: 200 },
      { name: 'Concombre', quantity_g: 80 },
      { name: 'Pain complet', quantity_g: 50 },
      { name: 'Ciboulette', quantity_g: 3 },
    ],
    steps: [
      'Mélanger le cottage cheese avec la ciboulette.',
      'Servir avec le concombre et le pain complet.',
    ],
    tags: ['snack', 'breakfast'],
    validated_by_dietitian: false,
  },
  // ── Phase 1 (bis) : +20 recettes pour élargir le pool de test ────────────────
  // Macros calées sur kcal = 4·P + 4·C + 9·F. Mix petit-déj / déj-dîner /
  // collation, options végétariennes et pescétariennes incluses.
  {
    id: 'r031',
    name_fr: 'Pain perdu protéiné',
    prep_time_min: 10,
    portions: 1,
    macros_per_portion: { kcal: 390, protein_g: 30, carbs_g: 45, fat_g: 10 },
    ingredients: [
      { name: 'Pain complet', quantity_g: 80 },
      { name: 'Œufs entiers', quantity_g: 100 },
      { name: 'Lait demi-écrémé', quantity_g: 100, unit: 'ml' },
      { name: 'Whey protéine vanille', quantity_g: 15 },
      { name: 'Cannelle', quantity_g: 2 },
    ],
    steps: [
      'Battre les œufs avec le lait, la whey et la cannelle.',
      'Tremper les tranches de pain dans le mélange.',
      'Dorer 2 min par face à la poêle antiadhésive.',
    ],
    tags: ['breakfast'],
    validated_by_dietitian: false,
  },
  {
    id: 'r032',
    name_fr: 'Bowl skyr, flocons & framboises',
    prep_time_min: 4,
    portions: 1,
    macros_per_portion: { kcal: 335, protein_g: 28, carbs_g: 40, fat_g: 7 },
    ingredients: [
      { name: 'Skyr', quantity_g: 200 },
      { name: 'Flocons d\'avoine', quantity_g: 40 },
      { name: 'Framboises', quantity_g: 60 },
      { name: 'Miel', quantity_g: 10 },
    ],
    steps: [
      'Verser le skyr dans un bol.',
      'Ajouter les flocons, les framboises et un filet de miel.',
    ],
    tags: ['breakfast', 'snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r033',
    name_fr: 'Œufs brouillés, avocat & pain complet',
    prep_time_min: 9,
    portions: 1,
    macros_per_portion: { kcal: 378, protein_g: 24, carbs_g: 30, fat_g: 18 },
    ingredients: [
      { name: 'Œufs entiers', quantity_g: 150 },
      { name: 'Avocat', quantity_g: 50 },
      { name: 'Pain complet', quantity_g: 60 },
      { name: 'Huile d\'olive', quantity_g: 4 },
    ],
    steps: [
      'Brouiller les œufs à feu doux dans l\'huile.',
      'Toaster le pain, écraser l\'avocat dessus.',
      'Servir les œufs sur la tartine.',
    ],
    tags: ['breakfast'],
    validated_by_dietitian: false,
  },
  {
    id: 'r034',
    name_fr: 'Cottage cheese, ananas & amandes',
    prep_time_min: 3,
    portions: 1,
    macros_per_portion: { kcal: 290, protein_g: 26, carbs_g: 24, fat_g: 10 },
    ingredients: [
      { name: 'Cottage cheese', quantity_g: 200 },
      { name: 'Ananas', quantity_g: 80 },
      { name: 'Amandes', quantity_g: 15 },
    ],
    steps: [
      'Verser le cottage cheese dans un bol.',
      'Ajouter les dés d\'ananas et les amandes concassées.',
    ],
    tags: ['breakfast', 'snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r035',
    name_fr: 'Galettes de riz, fromage frais & dinde',
    prep_time_min: 5,
    portions: 1,
    macros_per_portion: { kcal: 270, protein_g: 24, carbs_g: 30, fat_g: 6 },
    ingredients: [
      { name: 'Galettes de riz', quantity_g: 40 },
      { name: 'Fromage frais 0%', quantity_g: 60 },
      { name: 'Blanc de dinde', quantity_g: 60 },
    ],
    steps: [
      'Tartiner les galettes de fromage frais.',
      'Déposer les tranches de dinde dessus.',
    ],
    tags: ['snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r036',
    name_fr: 'Wrap thon & crudités',
    prep_time_min: 8,
    portions: 1,
    macros_per_portion: { kcal: 412, protein_g: 34, carbs_g: 42, fat_g: 12 },
    ingredients: [
      { name: 'Tortilla de blé', quantity_g: 60 },
      { name: 'Thon au naturel', quantity_g: 120 },
      { name: 'Maïs', quantity_g: 40 },
      { name: 'Salade verte', quantity_g: 30 },
      { name: 'Fromage frais 0%', quantity_g: 30 },
    ],
    steps: [
      'Étaler le fromage frais sur la tortilla.',
      'Garnir de thon égoutté, maïs et salade.',
      'Rouler le wrap et couper en deux.',
    ],
    tags: ['lunch'],
    validated_by_dietitian: false,
  },
  {
    id: 'r037',
    name_fr: 'Poke bowl saumon & edamame',
    prep_time_min: 12,
    portions: 1,
    macros_per_portion: { kcal: 496, protein_g: 36, carbs_g: 52, fat_g: 16 },
    ingredients: [
      { name: 'Saumon', quantity_g: 150 },
      { name: 'Riz basmati cru', quantity_g: 80 },
      { name: 'Edamame', quantity_g: 60 },
      { name: 'Avocat', quantity_g: 40 },
      { name: 'Sauce soja', quantity_g: 10 },
    ],
    steps: [
      'Cuire le riz et le laisser tiédir.',
      'Détailler le saumon cru en cubes.',
      'Dresser le bol avec edamame, avocat et sauce soja.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r038',
    name_fr: 'Poulet teriyaki & riz',
    prep_time_min: 15,
    portions: 1,
    macros_per_portion: { kcal: 501, protein_g: 45, carbs_g: 60, fat_g: 9 },
    ingredients: [
      { name: 'Blanc de poulet', quantity_g: 180 },
      { name: 'Riz basmati cru', quantity_g: 90 },
      { name: 'Sauce teriyaki', quantity_g: 25 },
      { name: 'Brocolis', quantity_g: 100 },
    ],
    steps: [
      'Cuire le riz à l\'eau.',
      'Saisir le poulet, glacer à la sauce teriyaki.',
      'Cuire les brocolis vapeur, assembler.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r039',
    name_fr: 'Boulettes de bœuf, semoule & courgettes',
    prep_time_min: 18,
    portions: 1,
    macros_per_portion: { kcal: 512, protein_g: 42, carbs_g: 50, fat_g: 16 },
    ingredients: [
      { name: 'Bœuf haché 5% MG', quantity_g: 170 },
      { name: 'Semoule', quantity_g: 70 },
      { name: 'Courgette', quantity_g: 120 },
      { name: 'Sauce tomate', quantity_g: 60 },
    ],
    steps: [
      'Former des boulettes et les saisir 6 min.',
      'Hydrater la semoule à l\'eau bouillante.',
      'Poêler les courgettes, mijoter avec la sauce tomate.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r040',
    name_fr: 'Cabillaud, boulgour & ratatouille',
    prep_time_min: 18,
    portions: 1,
    macros_per_portion: { kcal: 442, protein_g: 40, carbs_g: 48, fat_g: 10 },
    ingredients: [
      { name: 'Cabillaud', quantity_g: 180 },
      { name: 'Boulgour', quantity_g: 60 },
      { name: 'Ratatouille', quantity_g: 150 },
      { name: 'Huile d\'olive', quantity_g: 8 },
    ],
    steps: [
      'Cuire le boulgour à l\'eau 10 min.',
      'Poêler le cabillaud 3 min par face.',
      'Réchauffer la ratatouille, dresser.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r041',
    name_fr: 'Omelette jambon-fromage & salade',
    prep_time_min: 10,
    portions: 1,
    macros_per_portion: { kcal: 376, protein_g: 34, carbs_g: 6, fat_g: 24 },
    ingredients: [
      { name: 'Œufs entiers', quantity_g: 180 },
      { name: 'Jambon', quantity_g: 50 },
      { name: 'Emmental râpé', quantity_g: 30 },
      { name: 'Salade verte', quantity_g: 40 },
    ],
    steps: [
      'Battre les œufs, verser dans la poêle.',
      'Ajouter dés de jambon et emmental, plier.',
      'Servir avec la salade.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r042',
    name_fr: 'Buddha bowl pois chiches & feta',
    prep_time_min: 12,
    portions: 1,
    macros_per_portion: { kcal: 530, protein_g: 22, carbs_g: 70, fat_g: 18 },
    ingredients: [
      { name: 'Pois chiches cuits', quantity_g: 150 },
      { name: 'Quinoa cuit', quantity_g: 150 },
      { name: 'Feta', quantity_g: 40 },
      { name: 'Concombre', quantity_g: 60 },
      { name: 'Huile d\'olive', quantity_g: 8 },
    ],
    steps: [
      'Réchauffer le quinoa et les pois chiches.',
      'Couper le concombre et émietter la feta.',
      'Assembler le bowl, filet d\'huile d\'olive.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r043',
    name_fr: 'Pâtes thon & tomate',
    prep_time_min: 14,
    portions: 1,
    macros_per_portion: { kcal: 548, protein_g: 38, carbs_g: 72, fat_g: 12 },
    ingredients: [
      { name: 'Pâtes crues', quantity_g: 110 },
      { name: 'Thon au naturel', quantity_g: 120 },
      { name: 'Sauce tomate', quantity_g: 100 },
      { name: 'Parmesan', quantity_g: 15 },
    ],
    steps: [
      'Cuire les pâtes al dente.',
      'Chauffer la sauce tomate avec le thon.',
      'Mélanger, parsemer de parmesan.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r044',
    name_fr: 'Curry de poulet coco & riz',
    prep_time_min: 18,
    portions: 1,
    macros_per_portion: { kcal: 559, protein_g: 44, carbs_g: 62, fat_g: 15 },
    ingredients: [
      { name: 'Blanc de poulet', quantity_g: 170 },
      { name: 'Riz basmati cru', quantity_g: 90 },
      { name: 'Lait de coco', quantity_g: 60, unit: 'ml' },
      { name: 'Pâte de curry', quantity_g: 20 },
      { name: 'Poivrons', quantity_g: 80 },
    ],
    steps: [
      'Cuire le riz à l\'eau.',
      'Saisir le poulet avec la pâte de curry.',
      'Ajouter lait de coco et poivrons, mijoter 8 min.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r045',
    name_fr: 'Thon snacké, patate douce & haricots verts',
    prep_time_min: 16,
    portions: 1,
    macros_per_portion: { kcal: 470, protein_g: 42, carbs_g: 44, fat_g: 14 },
    ingredients: [
      { name: 'Thon frais', quantity_g: 170 },
      { name: 'Patate douce', quantity_g: 150 },
      { name: 'Haricots verts', quantity_g: 120 },
      { name: 'Huile d\'olive', quantity_g: 8 },
    ],
    steps: [
      'Cuire la patate douce et les haricots verts vapeur.',
      'Snacker le thon 1 min par face (cœur rosé).',
      'Dresser avec un filet d\'huile d\'olive.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r046',
    name_fr: 'Chili végétarien & riz',
    prep_time_min: 20,
    portions: 1,
    macros_per_portion: { kcal: 506, protein_g: 22, carbs_g: 82, fat_g: 10 },
    ingredients: [
      { name: 'Haricots rouges cuits', quantity_g: 150 },
      { name: 'Riz basmati cru', quantity_g: 70 },
      { name: 'Maïs', quantity_g: 50 },
      { name: 'Sauce tomate', quantity_g: 80 },
      { name: 'Oignon', quantity_g: 40 },
    ],
    steps: [
      'Faire revenir l\'oignon, ajouter haricots et maïs.',
      'Incorporer la sauce tomate et les épices, mijoter 10 min.',
      'Servir sur le riz cuit.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
  {
    id: 'r047',
    name_fr: 'Tartines saumon fumé & fromage frais',
    prep_time_min: 6,
    portions: 1,
    macros_per_portion: { kcal: 416, protein_g: 28, carbs_g: 40, fat_g: 16 },
    ingredients: [
      { name: 'Pain complet', quantity_g: 80 },
      { name: 'Saumon fumé', quantity_g: 80 },
      { name: 'Fromage frais 0%', quantity_g: 40 },
      { name: 'Aneth', quantity_g: 3 },
    ],
    steps: [
      'Toaster le pain complet.',
      'Étaler le fromage frais, déposer le saumon fumé.',
      'Parsemer d\'aneth.',
    ],
    tags: ['breakfast', 'lunch'],
    validated_by_dietitian: false,
  },
  {
    id: 'r048',
    name_fr: 'Shake protéiné choco-banane',
    prep_time_min: 2,
    portions: 1,
    macros_per_portion: { kcal: 326, protein_g: 32, carbs_g: 36, fat_g: 6 },
    ingredients: [
      { name: 'Whey protéine chocolat', quantity_g: 30 },
      { name: 'Banane', quantity_g: 100 },
      { name: 'Lait demi-écrémé', quantity_g: 250, unit: 'ml' },
    ],
    steps: [
      'Mixer tous les ingrédients 30 secondes.',
      'Servir bien frais.',
    ],
    tags: ['snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r049',
    name_fr: 'Yaourt grec, granola & fruits rouges',
    prep_time_min: 3,
    portions: 1,
    macros_per_portion: { kcal: 304, protein_g: 20, carbs_g: 38, fat_g: 8 },
    ingredients: [
      { name: 'Yaourt grec', quantity_g: 200 },
      { name: 'Granola', quantity_g: 40 },
      { name: 'Fruits rouges', quantity_g: 60 },
      { name: 'Miel', quantity_g: 8 },
    ],
    steps: [
      'Verser le yaourt grec dans un bol.',
      'Ajouter granola, fruits rouges et miel.',
    ],
    tags: ['breakfast', 'snack'],
    validated_by_dietitian: false,
  },
  {
    id: 'r050',
    name_fr: 'Riz cantonais au poulet',
    prep_time_min: 16,
    portions: 1,
    macros_per_portion: { kcal: 508, protein_g: 34, carbs_g: 66, fat_g: 12 },
    ingredients: [
      { name: 'Riz basmati cru', quantity_g: 100 },
      { name: 'Blanc de poulet', quantity_g: 120 },
      { name: 'Œuf', quantity_g: 50 },
      { name: 'Petits pois', quantity_g: 50 },
      { name: 'Sauce soja', quantity_g: 12 },
    ],
    steps: [
      'Cuire le riz et le laisser refroidir.',
      'Saisir le poulet émincé, ajouter l\'œuf brouillé.',
      'Faire sauter avec riz, petits pois et sauce soja.',
    ],
    tags: ['lunch', 'dinner'],
    validated_by_dietitian: false,
  },
];

// ── Overrides perso (recettes éditées par l'utilisateur) ─────────────────────
// Registre module-level : la base reste figée (RECIPES_PLACEHOLDER), l'utilisateur
// peut remplacer une recette par SA version. Le moteur, le garde-manger et les
// écrans lisent les recettes EFFECTIVES (base ⊕ overrides) via ces accesseurs.
// Le registre est hydraté au démarrage depuis AsyncStorage (cf. useRecipeOverrides)
// pour que la génération (fonction pure, hors React) voie les overrides.

let recipeOverrides: Record<string, Recipe> = {};

export function setRecipeOverrides(map: Record<string, Recipe> | null | undefined): void {
  recipeOverrides = map ?? {};
}

/** Liste effective : chaque recette de base remplacée par sa version perso si elle existe. */
export function getEffectiveRecipes(): Recipe[] {
  return RECIPES_PLACEHOLDER.map((r) => recipeOverrides[r.id] ?? r);
}

/** Recette effective par id (override prioritaire). */
export function getRecipeById(id: string): Recipe | undefined {
  return recipeOverrides[id] ?? RECIPES_PLACEHOLDER.find((r) => r.id === id);
}

/** Recette de base d'origine (pour le « réinitialiser »). */
export function getBaseRecipe(id: string): Recipe | undefined {
  return RECIPES_PLACEHOLDER.find((r) => r.id === id);
}

export function isOverridden(id: string): boolean {
  return Object.prototype.hasOwnProperty.call(recipeOverrides, id);
}
